_config/lib: !include "../config/hpack-common.yaml"

name:       luna-runtime
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src

dependencies:
    - async
    - base
    - containers
    - luna-core
    - luna-future
    - mtl
    - prologue

default-extensions: *luna-extensions

