_config/lib: !include "../../../config/hpack-common.yaml"

name       : luna-syntax-text-lexer
version    : "0.2"
author     : Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src
        - src-libs/attoparsec-text32
        - src-libs/conduit-utils
        - src-libs/parsing
    other-modules: Paths_luna_syntax_text_lexer

benchmarks:
    lexer-benchmark:
        main: Main.hs
        source-dirs: test/bench
        dependencies:
            - attoparsec
            - conduit
            - conduit-combinators
            - conduit-extra
            - criterion
            - luna-syntax-text-lexer
            - random
            - timeit

dependencies:
    - attoparsec
    - base
    - bytestring
    - conduit
    - conduit-combinators
    - containers
    - convert
    - fingertree
    - functor-utils
    - layered-state
    - lens
    - luna-core
    - luna-syntax-text-model
    - luna-text-processing
    - mtl
    - prologue
    - resourcet
    - text
    - vector
    - vector-text

default-extensions: *luna-extensions

