_config/lib: !include "../config/hpack-common.yaml"

name:       luna-stdlib
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src
    dependencies:
        - aeson
        - async
        - authenticate-oauth
        - base
        - bytestring
        - case-insensitive
        - containers
        - data-msgpack
        - deepseq
        - directory
        - errors
        - exceptions
        - filepath
        - hashable
        - http-client
        - http-client-tls
        - http-conduit
        - http-types
        - lens
        - libffi
        - luna-core
        - luna-datafile
        - luna-package
        - luna-passes
        - luna-path
        - luna-runtime
        - luna-syntax-text-prettyprint
        - mtl
        - network
        - process
        - prologue
        - path
        - path-io
        - random
        - safe
        - safe-exceptions
        - scientific
        - text
        - time
        - transformers
        - typelevel
        - unordered-containers
        - uuid
        - vector
        - websockets
        - wuss

when:
    - condition: os(windows)
      then:
          dependencies: Win32
      else:
          dependencies: unix

default-extensions: *luna-extensions

