_config/lib: !include "../config/hpack-common.yaml"

name:       luna-passes
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src
    dependencies:
        - async
        - base
        - container
        - containers
        - filepath
        - lens
        - luna-exception
        - luna-cpp-containers
        - luna-data-storable
        - luna-data-construction
        - luna-foreign-utils
        - luna-future
        - luna-generic-traversable
        - luna-runtime
        - luna-syntax-text-parser
        - luna-syntax-text-builder
        - luna-syntax-text-lexer
        - luna-syntax-text-model
        - luna-syntax-text-prettyprint
        - luna-text-processing
        - layered-state
        - luna-core
        - luna-debug
        - mtl
        - prologue >= 3.0.0
        - storable-tuple
        - text
        - transformers
        - uuid-types

default-extensions: *luna-extensions

