resolver: lts-12.26
name: luna

packages:
    - githash-0.1.3.0
    - hspec-expectations-lifted-0.10.0
    - hspec-megaparsec-1.1.0
    - megaparsec-6.5.0
    - neat-interpolation-0.3.2.2
    - placeholders-0.1
    - rdtsc-1.3.0.1
    - mtl-c-0.1.1
    - weigh-0.0.13
    - path-io-1.4.2
