_config/lib: !include "../../../config/hpack-common.yaml"

name       : luna-syntax-text-parser
version    : "0.2"
author     : Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src
        - src-libs

tests:
    spec:
        main: Main.hs
        source-dirs: test/spec
        dependencies:
            - container
            - directory
            - filepath
            - hspec
            - hspec-core
            - hspec-expectations-lifted
            - hspec-megaparsec
            - luna-core
            - luna-syntax-text-lexer
            - luna-syntax-text-parser
            - open-browser
            - prologue
            - template-haskell

benchmarks:
    array-benchmark:
        main: Main.hs
        source-dirs:
            - test/bench
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N
            - -with-rtsopts=-T
        dependencies:
            - attoparsec
            - base
            - criterion
            - frisby
            - text

dependencies:
    - attoparsec
    - base
    - container
    - containers
    - convert
    - layered-state
    - layouting
    - lens
    - lens-utils
    - luna-core
    - luna-cpp-containers
    - luna-data-storable
    - luna-foreign-utils
    - luna-generic-traversable
    - luna-nested-containers
    - luna-parser-utils
    - luna-syntax-definition
    - luna-syntax-text-lexer
    - luna-syntax-text-model
    - luna-text-processing
    - megaparsec == 6.5.0
    - mtl
    - prologue
    - text
    - vector
    - vector-text

default-extensions: *luna-extensions

