_config/lib: !include "../config/hpack-common.yaml"

name:       luna-package
version:    "0.2"
author:     Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src

data-files:
    - ./data/licenses/*

tests:
    spec:
        main: Main.hs
        source-dirs: test/spec
        dependencies:
            - bytestring
            - directory
            - filepath
            - hspec
            - hspec-jenkins
            - luna-ci
            - luna-package
            - luna-yaml-utils
            - megaparsec
            - open-browser
            - temporary-rc

dependencies:
    - aeson
    - base
    - bimap
    - containers
    - exceptions
    - filemanip
    - hspec
    - hspec-megaparsec
    - lens
    - lens-utils
    - luna-core
    - luna-datafile
    - luna-exception
    - luna-parser-utils
    - luna-path
    - luna-syntax-text-lexer
    - megaparsec
    - mtl
    - path >= 0.6.0
    - path-io >= 1.4.0
    - prologue
    - safe-exceptions
    - text
    - yaml

default-extensions: *luna-extensions

